# Pandas - Groupby

In [4]:
import numpy as np
import pandas as pd

In [10]:
data = {'Company' : ['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [11]:
df  = pd.DataFrame(data)

In [12]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [37]:
byComp =  df.groupby('Company')['Sales']

In [38]:
byComp.mean(numeric_only=True)

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [39]:
byComp.sum()

Company
FB      593
GOOG    320
MSFT    464
Name: Sales, dtype: int64

In [40]:
byComp.std()

Company
FB       75.660426
GOOG     56.568542
MSFT    152.735065
Name: Sales, dtype: float64

In [42]:
byComp.sum().loc['FB']

np.int64(593)

In [45]:
df.groupby('Company').count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [46]:
df.groupby('Company').min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [51]:
df.groupby('Company').describe().transpose()['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64