# Data Input and Output
- CSV
- EXCEL
- HTML
- SQL

In [1]:
import pandas as pd

In [2]:
pwd

'C:\\Users\\HarshMistry\\training-crest\\07 Python DS & ML\\05 Numpy'

In [5]:
pd.read_csv('example.csv')

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
df = pd.read_csv('example.csv')

In [11]:
df.to_csv('My_output',index=False)

In [12]:
pd.read_csv('My_output')

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [13]:
conda install xlrd

Jupyter detected...
3 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\HarshMistry\anaconda3

  added / updated specs:
    - xlrd


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-26.1.0               |  py313haa95532_0         1.2 MB
    openssl-3.0.19             |       hbb43b14_0         6.9 MB
    xlrd-2.0.2                 |     pyhd3eb1b0_0          91 KB
    ------------------------------------------------------------
                                           Total:         8.3 MB

The following NEW packages will be INSTALLED:

  xlrd               pkgs/main/noarch::xlrd-2.0.2-pyhd3eb1b0_0

The following packages will be UPDATED:

  ca-certificates                      2025.11.4-haa95532_0 --> 2025.12.2-haa95532_0
  certifi                        2025.11.12-py313haa95532_0 --> 2026.01.04-py313haa95532_0
  conda                             25.11.0-py313haa95532_0 --> 26.1.0-py313haa95532_0
  openssl                                 3.0.18-h543e019_0 --> 3.0.19-hbb43b14_0



Downloading and Extracting Packages: ...working...
openssl-3.0.19       | 6.9 MB    |            |   0%

conda-26.1.0         | 1.2 MB    |            |   0%


xlrd-2.0.2           | 91 KB     |            |   0%
openssl-3.0.19       | 6.9 MB    |            |   0%
openssl-3.0.19       | 6.9 MB    | 2          |   3%

conda-26.1.0         | 1.2 MB    | 1          |   1%
openssl-3.0.19       | 6.9 MB    | 5          |   6%


xlrd-2.0.2           | 91 KB     | #7         |  18%

conda-26.1.0         | 1.2 MB    | 8          |   9%
openssl-3.0.19       | 6.9 MB    | #1         |  11%


xlrd-2.0.2           | 91 KB     | #####2     |  53%


xlrd-2.0.2           | 91 KB     | ########## | 100%


xlrd-2.0.2           | 91 KB     | ########## | 100%


xlrd-2.0.2           | 91 KB     | ########## | 100%
openssl-3.0.19       | 6.9 MB    | #4         |  15%

conda-26.1.0         | 1.2 MB    | #4         |  14%
openssl-3.0.19       | 6.9 MB    | ##         |  21%

conda-26.1.0         | 1.2 MB    | ##         |  21%
openssl-3.0.19       | 6.9 MB    | ##4        |  25%

conda-26.1.0         | 1.2 MB    | ###3       |  33%
openssl-3.0.19       | 6.9 MB    | ##8        |  28%

conda-26.1.0         | 1.2 MB    | ###9       |  40%
openssl-3.0.19       | 6.9 MB    | ###1       |  31%

conda-26.1.0         | 1.2 MB    | ####8      |  49%
openssl-3.0.19       | 6.9 MB    | ###4       |  35%

conda-26.1.0         | 1.2 MB    | #####6     |  56%

conda-26.1.0         | 1.2 MB    | ######4    |  64%
openssl-3.0.19       | 6.9 MB    | ###7       |  38%

conda-26.1.0         | 1.2 MB    | #######1   |  72%
openssl-3.0.19       | 6.9 MB    | ####5      |  45%

conda-26.1.0         | 1.2 MB    | #######9   |  80%
openssl-3.0.19       | 6.9 MB    | ####9      |  49%

conda-26.1.0         | 1.2 MB    | ########7  |  87%
openssl-3.0.19       | 6.9 MB    | #####3     |  53%

conda-26.1.0         | 1.2 MB    | #########4 |  95%
openssl-3.0.19       | 6.9 MB    | #####6     |  56%

conda-26.1.0         | 1.2 MB    | ########## | 100%
openssl-3.0.19       | 6.9 MB    | ######     |  61%
openssl-3.0.19       | 6.9 MB    | ######4    |  64%
openssl-3.0.19       | 6.9 MB    | ######7    |  67%
openssl-3.0.19       | 6.9 MB    | #######    |  71%
openssl-3.0.19       | 6.9 MB    | #######2   |  73%
openssl-3.0.19       | 6.9 MB    | #######7   |  77%
openssl-3.0.19       | 6.9 MB    | ########   |  81%
openssl-3.0.19       | 6.9 MB    | ########5  |  86%
openssl-3.0.19       | 6.9 MB    | ########9  |  89%
openssl-3.0.19       | 6.9 MB    | #########6 |  96%
openssl-3.0.19       | 6.9 MB    | ########## | 100%
openssl-3.0.19       | 6.9 MB    | ########## | 100%

conda-26.1.0         | 1.2 MB    | ########## | 100%
openssl-3.0.19       | 6.9 MB    | ########## | 100%






                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [17]:
pd.read_excel('Excel_Sample.xlsx',sheet_name = 'Sheet1')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [18]:
df.to_excel('Excel_Sample.xlsx',sheet_name='NewSheet')

In [19]:
data = pd.read_html('https://www.fdic.gov/bank-failures/failed-bank-list')

In [20]:
type(data)

list

In [21]:
data[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546

In [22]:
from sqlalchemy import create_engine

In [23]:
engine = create_engine('sqlite:///:memory:')

In [24]:
df.to_sql('my_table',engine)

4

In [25]:
sqldf = pd.read_sql('my_table',con = engine)

In [26]:
sqldf

   index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15